### ISSUE TITLE
Github Action만으로 가동되는 봇으로 수정하기

### ISSUE THREAD

**Issue by lens0021** [femiwiki/tweetbot#12]
현재는 crontab을 포함한 도커 이미지를 빌드하고, 그 이미지를 AWS EC2 인스턴스 위에서 실행하고 있습니다.

이 봇이 하는 작업이 비교적 간단하여 모든 동작을 Github Action으로 이전하는 것이 가능해 보이며, 이에 따라 도커 관련 부분은 덜어내고 주기적으로 파이썬만 실행하도록 수정합니다.

- [x] 임시데이터 저장을 파일이 아닌 온라인에 하기 https://github.com/femiwiki/tweetbot/issues/9
- [x] 깃헙 액션 작성
- [x] Docker Hub에 있는 트윗봇 도커 이미지 repository에 사용되지 않음 경고 추가하기
- [x] github repository 세팅에 Deploy Key로 Docker Cloud가 등록되어 있는 것 지우기
- AWS에서 봇 지우기
  - [x] https://github.com/femiwiki/docker-mediawiki/blob/master/bots.yml 수정하고 deploy 하기
  - [x] `/srv/tweetbot` 지우기
  - [x] `bot-secret.env` 도 고치기
- [x] 봇이 제 시간에 잘 트윗하는지 주시하기(원하는 트윗 시간은 1시 5시 9시 13시 17시 21시입니다)

**Comment by lens0021** [comment]
아직 다른 작업이 남아 다시 엽니다

**Comment by love-adela** [comment]
와 정말 너무 고생 많으셨습니다!!

**Comment by lens0021** [comment]
트윗 https://twitter.com/Femiwikidotcome/status/1228953573762850817
문서 편집 https://femiwiki.com/w/Special:Diff/158549
