### ISSUE TITLE
글자제한 늘리기

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/tweetbot#3]
140, 150자보다 훨씬 커도 되는것으로 보임

**Comment by lens0021** [comment]
python-twitter의  [twitter.twitter_utils.calc_expected_status_length](https://python-twitter.readthedocs.io/en/latest/twitter.html#twitter.twitter_utils.calc_expected_status_length)라는 함수가 url까지 변환해서 알아서 잘 계산해주는 것으로 보여 이걸 쓰도록 작업중입니다

**Comment by simnalamburt** [comment]
👍
